### ISSUE TITLE
Axonops gui fails to render. 

### ISSUE THREAD

**Issue by gruaig** [axonops/documentation#1]
Axonops UI fails to render. After accepting the T&C it errors out.

index.js:54 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at n.<anonymous> (index.js:54)
    at w (commons.a9239c8915bb731b12aa.js:36)
    at Generator._invoke (commons.a9239c8915bb731b12aa.js:36)
    at Generator.e.(:3000/anonymous function) [as next] (http://11.11.206.10:3000/_next/static/chunks/commons.a9239c8915bb731b12aa.js:36:538042)
    at ue (index.js:54)
    at a (index.js:54)

Also the /eula page returns a 404.
![screenshot from 2019-02-20 22-39-44](https://user-images.githubusercontent.com/5451282/53129821-87069980-3560-11e9-9aa3-8a4f0cf5ef46.png)
![screenshot from 2019-02-20 22-40-00](https://user-images.githubusercontent.com/5451282/53129822-879f3000-3560-11e9-8fda-d9cff1d06ad8.png)

**Comment by DigitalMarc** [comment]
Thanks for your feedback.
It looks that the EULA request is made upon port 3000 when axon-server default API port is 8080.
Can you verify that your axon-dash.yaml is something like the following?: 
```
axon-dash:
  host: 0.0.0.0
  port: 3000

axon-server:
  public_endpoints: "http://11.11.206.10:8080" 
  context_path: ""
```
The config assume that axon-server is listening at `11.11.206.10:8080`

**Comment by gruaig** [comment]
This is my config
axon-dash:
  host: 0.0.0.0
  port: 3000

axon-server:
  public_endpoints: "http://11.11.206.10:8080" 
  context: ""

**Comment by DigitalMarc** [comment]
It may be also a version problem, can you verify that you are running with the following version:
axon-server: 0.0.13
axon-dash:  0.0.7

**Comment by gruaig** [comment]
---> Package axon-dash.x86_64 0:0.0.4-1 will be updated
---> Package axon-dash.x86_64 0:0.0.6-1 will be an update

Did the trick in yum. You can close the issue if you like. 

Have you tried using a docker image for cassandra I'm building one now with your agent inside.

Sean

**Comment by DigitalMarc** [comment]
Great!

We haven't had time to build any docker image yet but that's on our roadmap. Let us know how it goes!!

Marc
